const TC = {
  normal:   {bg:'#6b6b5e', text:'#e8e8d8'},
  fire:     {bg:'#c0521a', text:'#ffe8d0'},
  water:    {bg:'#1a4fa0', text:'#d0e8ff'},
  electric: {bg:'#b89000', text:'#fff8c0'},
  grass:    {bg:'#2d7a2d', text:'#d0f0d0'},
  ice:      {bg:'#2a8888', text:'#c8f0f0'},
  fighting: {bg:'#8a1a1a', text:'#ffd8d8'},
  poison:   {bg:'#6a1a8a', text:'#f0d0ff'},
  ground:   {bg:'#8a6a10', text:'#fff0c0'},
  flying:   {bg:'#4a3a9a', text:'#e0d8ff'},
  psychic:  {bg:'#a01a5a', text:'#ffd0e8'},
  bug:      {bg:'#4a5a10', text:'#e8f0b0'},
  rock:     {bg:'#6a5a18', text:'#f0e8c0'},
  ghost:    {bg:'#3a2a6a', text:'#ddd0ff'},
  dragon:   {bg:'#2a0a9a', text:'#d0c8ff'},
  dark:     {bg:'#2a2018', text:'#d8d0c0'},
  steel:    {bg:'#3a3a5a', text:'#d8d8f0'},
  fairy:    {bg:'#902050', text:'#ffd0e0'},
};

const typeChart = {
  normal    : { ghost:0, fighting:2 },
  fighting  : { rock:0.5, bug:0.5, dark:0.5, flying:2, psychic:2, fairy:2 },
  flying    : { ground:0, fighting:0.5, bug:0.5, grass:0.5, rock:2, electric:2, ice:2 },
  poison    : { fighting:0.5, poison:0.5, bug:0.5, grass:0.5, fairy:0.5, ground:2, psychic:2 },
  ground    : { electric:0, poison:0.5, rock:0.5, water:2, grass:2, ice:2 },
  rock      : { normal:0.5, flying:0.5, poison:0.5, fire:0.5, fighting:2, ground:2, steel:2, water:2, grass:2 },
  bug       : { fighting:0.5, ground:0.5, grass:0.5, flying:2, rock:2, fire:2 },
  ghost     : { normal:0, fighting:0, poison:0.5, bug:0.5, ghost:2, dark:2 },
  steel     : { poison:0, normal:0.5, flying:0.5, rock:0.5, bug:0.5, steel:0.5, grass:0.5, psychic:0.5, ice:0.5, dragon:0.5, fairy:0.5, fighting:2, ground:2, fire:2 },
  fire      : { bug:0.5, steel:0.5, fire:0.5, grass:0.5, ice:0.5, fairy:0.5, ground:2, rock:2, water:2 },
  water     : { steel:0.5, fire:0.5, water:0.5, ice:0.5, grass:2, electric:2 },
  grass     : { ground:0.5, water:0.5, grass:0.5, electric:0.5, flying:2, poison:2, bug:2, fire:2, ice:2 },
  electric  : { flying:0.5, steel:0.5, electric:0.5, ground:2 },
  psychic   : { fighting:0.5, psychic:0.5, bug:2, ghost:2, dark:2 },
  ice       : { ice:0.5, fighting:2, rock:2, steel:2, fire:2 },
  dragon    : { fire:0.5, water:0.5, grass:0.5, electric:0.5, ice:2, dragon:2, fairy:2 },
  dark      : { psychic:0, ghost:0.5, dark:0.5, fighting:2, bug:2, fairy:2 },
  fairy     : { dragon:0, fighting:0.5, bug:0.5, dark:0.5, poison:2, steel:2 },
};

// Types that didn't exist in earlier gens. null means "treat as Normal" for damage calc purposes.
// Fairy was added in Gen 6; Dark and Steel in Gen 2.
const GEN_OVERRIDES = {
  1: {fairy:null, dark:null, steel:null},
  2: {fairy:null},
  3: {fairy:null},
  4: {fairy:null},
  5: {fairy:null},
};

const GEN_VGS = {
  1: ['red-blue','yellow'],
  2: ['gold-silver','crystal'],
  3: ['ruby-sapphire','emerald','firered-leafgreen'],
  4: ['diamond-pearl','platinum','heartgold-soulsilver'],
  5: ['black-white','black-2-white-2'],
  6: ['x-y','omega-ruby-alpha-sapphire'],
  7: ['sun-moon','ultra-sun-ultra-moon'],
  8: ['sword-shield','brilliant-diamond-and-shining-pearl'],
  9: ['scarlet-violet'],
};

const REL_ABILITIES = {
  'levitate':       {immune:['ground']},
  'flash-fire':     {immune:['fire']},
  'volt-absorb':    {immune:['electric']},
  'water-absorb':   {immune:['water']},
  'storm-drain':    {immune:['water']},
  'earth-eater':    {immune:['ground']},
  'dry-skin':       {immune:['water'], weak:['fire']},
  'sap-sipper':     {immune:['grass']},
  'motor-drive':    {immune:['electric']},
  'lightning-rod':  {immune:['electric']},
  'well-baked-body':{immune:['fire']},
  'wind-rider':     {immune:['flying']},
  'purifying-salt': {immune:['ghost']},
  'heatproof':      {halve:['fire']},
  'thick-fat':      {halve:['fire','ice']},
  'wonder-guard':   {special:'wonderguard'},
};


const STAT_CONFIG = [
  {key:'hp',             statKey:'hp',    color:'#4caf50'},
  {key:'attack',         statKey:'atk',   color:'#f44336'},
  {key:'defense',        statKey:'def',   color:'#ff9800'},
  {key:'special-attack', statKey:'spatk', color:'#2196f3'},
  {key:'special-defense',statKey:'spdef', color:'#9c27b0'},
  {key:'speed',          statKey:'speed', color:'#e91e63'},
];
const STAT_MAX = 255;

const MOVE_TABS = [
  {key:'level-up',    labelKey:'levelUp'},
  {key:'machine',     labelKey:'tmhm'},
  {key:'egg',         labelKey:'breeding'},
  {key:'tutor',       labelKey:'tutor'},
  {key:'form-change', labelKey:'priorEvo'},
];

// --- Localization ---

let currentLang = localStorage.getItem('wdex_lang') || 'en';

const LANG_LABELS = {
  'en':      'English',
  'de':      'Deutsch',
  'fr':      'Français',
  'es':      'Español',
  'it':      'Italiano',
  'ja':      '日本語',
  'ko':      '한국어',
  'zh-Hans': '中文(简体)',
  'zh-Hant': '中文(繁體)',
  'ja-Hrkt': '日本語(かな)',
  'roomaji': 'Rōmaji',
};

function getLocalizedName(entries, lang) {
  if (!entries || !entries.length) return '';
  return (entries.find(e => e.language.name === lang)
    || entries.find(e => e.language.name === 'en')
    || entries[0])?.name || '';
}

function getLocalizedTypeName(type, lang) {
  return getLocalizedName(typeNamesCache[type], lang) || type;
}

const UI_STRINGS = {
  en: {
    weaknesses:'WEAKNESSES', baseStats:'BASE STATS', abilities:'ABILITIES',
    evoChain:'EVOLUTION CHAIN', forms:'FORMS', default_:'DEFAULT', with_:'WITH',
    weak4:'WEAKNESS ×4', weak2:'WEAKNESS ×2', immune:'IMMUNE ×0',
    resist2:'RESISTANT ×½', resist4:'RESISTANT ×¼',
    noMatchups:'No notable matchups',
    hp:'HP', atk:'Atk', def:'Def', spatk:'SpAtk', spdef:'SpDef', speed:'Speed',
    special:'Special', total:'Total',
    levelUp:'Level Up', tmhm:'TM / HM', breeding:'Breeding', tutor:'Tutor', priorEvo:'Prior Evo',
    colLv:'LV', colMove:'MOVE', colType:'TYPE', colCat:'CAT', colPwr:'PWR', colAcc:'ACC', colPp:'PP',
    catPhysical:'Physical', catSpecial:'Special', catStatus:'Status',
    ha:'HA', movesBtn:'Moves', evolvesFrom:'evolves from',
    friendship:'friendship', trade:'trade', day:'day', night:'night',
    rain:'rain', flip:'flip', beauty:'beauty', affection:'affection', special_:'special',
    loading:'Loading…', noDesc:'No description available.',
    failedMoves:'Failed to load moves.', noMoveData:'No move data available.',
    noMovesInCat:'No moves in this category.',
    subtitle:'Type a Pokémon name to see its weaknesses',
    searchPlaceholder:'e.g. poochyena, charizard…',
    advancedBtn:'Advanced', genLabel:'Generation', latestGen:'Latest (Gen 9)',
    abilityLabel:'Ability override', noneOption:'— none —', languageLabel:'Language',
    searchHint:'No results — try in English',
    clearHistory:'Clear history',
  },
  de: {
    weaknesses:'SCHWÄCHEN', baseStats:'BASISWERTE', abilities:'FÄHIGKEITEN',
    evoChain:'ENTWICKLUNG', forms:'FORMEN', default_:'STANDARD', with_:'MIT',
    weak4:'SCHWÄCHE ×4', weak2:'SCHWÄCHE ×2', immune:'IMMUN ×0',
    resist2:'RESISTENT ×½', resist4:'RESISTENT ×¼',
    noMatchups:'Keine besonderen Treffer',
    hp:'KP', atk:'Ang', def:'Vert', spatk:'Sp.Ang', spdef:'Sp.Vert', speed:'Init',
    special:'Spezial', total:'Gesamt',
    levelUp:'Level Up', tmhm:'TM / VM', breeding:'Zucht', tutor:'Lehrer', priorEvo:'Vorstufe',
    colLv:'LV', colMove:'ATTACKE', colType:'TYP', colCat:'KAT', colPwr:'ST', colAcc:'Gen', colPp:'AP',
    catPhysical:'Physisch', catSpecial:'Spezial', catStatus:'Status',
    ha:'HA', movesBtn:'Attacken', evolvesFrom:'entwickelt sich aus',
    friendship:'Freundschaft', trade:'Tausch', day:'Tag', night:'Nacht',
    rain:'Regen', flip:'Drehen', beauty:'Schönheit', affection:'Zuneigung', special_:'spezial',
    loading:'Lädt…', noDesc:'Keine Beschreibung verfügbar.',
    failedMoves:'Attacken konnten nicht geladen werden.', noMoveData:'Keine Attackendaten.',
    noMovesInCat:'Keine Attacken in dieser Kategorie.',
    subtitle:'Pokémon-Namen eingeben, um Schwächen zu sehen',
    searchPlaceholder:'z.B. nachtara, glurak…',
    advancedBtn:'Erweitert', genLabel:'Generation', latestGen:'Aktuell (Gen 9)',
    abilityLabel:'Fähigkeit', noneOption:'— keine —', languageLabel:'Sprache',
    searchHint:'Keine Treffer – auf Englisch versuchen',
    clearHistory:'Verlauf löschen',
  },
  fr: {
    weaknesses:'FAIBLESSES', baseStats:'STATS DE BASE', abilities:'TALENTS',
    evoChain:"CHAÎNE D'ÉVOLUTION", forms:'FORMES', default_:'DÉFAUT', with_:'AVEC',
    weak4:'FAIBLESSE ×4', weak2:'FAIBLESSE ×2', immune:'IMMUNITÉ ×0',
    resist2:'RÉSISTANT ×½', resist4:'RÉSISTANT ×¼',
    noMatchups:'Aucun résultat notable',
    hp:'PV', atk:'Att', def:'Déf', spatk:'Att.Sp', spdef:'Déf.Sp', speed:'Vit',
    special:'Spécial', total:'Total',
    levelUp:'Niveau', tmhm:'CS / CO', breeding:'Reproduction', tutor:'Tuteur', priorEvo:'Pré-évol.',
    colLv:'Nv', colMove:'CAPACITÉ', colType:'TYPE', colCat:'CAT', colPwr:'PUI', colAcc:'PRÉ', colPp:'PP',
    catPhysical:'Physique', catSpecial:'Spécial', catStatus:'Statut',
    ha:'CS', movesBtn:'Capacités', evolvesFrom:'évolue de',
    friendship:'amitié', trade:'échange', day:'jour', night:'nuit',
    rain:'pluie', flip:'retourner', beauty:'beauté', affection:'affection', special_:'spécial',
    loading:'Chargement…', noDesc:'Aucune description disponible.',
    failedMoves:'Échec du chargement.', noMoveData:'Aucune donnée de capacité.',
    noMovesInCat:'Aucune capacité dans cette catégorie.',
    subtitle:'Saisissez un nom de Pokémon pour voir ses faiblesses',
    searchPlaceholder:'ex. medhyena, dracaufeu…',
    advancedBtn:'Avancé', genLabel:'Génération', latestGen:'Récent (Gen 9)',
    abilityLabel:'Remplacer talent', noneOption:'— aucun —', languageLabel:'Langue',
    searchHint:'Aucun résultat — essayer en anglais',
    clearHistory:'Effacer l\'historique',
  },
  es: {
    weaknesses:'DEBILIDADES', baseStats:'ESTADÍSTICAS BASE', abilities:'HABILIDADES',
    evoChain:'CADENA EVOLUTIVA', forms:'FORMAS', default_:'BASE', with_:'CON',
    weak4:'DEBILIDAD ×4', weak2:'DEBILIDAD ×2', immune:'INMUNE ×0',
    resist2:'RESISTENTE ×½', resist4:'RESISTENTE ×¼',
    noMatchups:'Sin resultados notables',
    hp:'PS', atk:'Atq', def:'Def', spatk:'At.Esp', spdef:'De.Esp', speed:'Vel',
    special:'Especial', total:'Total',
    levelUp:'Subida niv.', tmhm:'MT / MO', breeding:'Cría', tutor:'Tutor', priorEvo:'Preevo.',
    colLv:'NV', colMove:'MOVIMIENTO', colType:'TIPO', colCat:'CAT', colPwr:'POT', colAcc:'PRE', colPp:'PP',
    catPhysical:'Físico', catSpecial:'Especial', catStatus:'Estado',
    ha:'HA', movesBtn:'Movimientos', evolvesFrom:'evoluciona de',
    friendship:'amistad', trade:'intercambio', day:'día', night:'noche',
    rain:'lluvia', flip:'girar', beauty:'belleza', affection:'afecto', special_:'especial',
    loading:'Cargando…', noDesc:'Sin descripción disponible.',
    failedMoves:'Error al cargar movimientos.', noMoveData:'Sin datos de movimientos.',
    noMovesInCat:'Sin movimientos en esta categoría.',
    subtitle:'Escribe el nombre de un Pokémon para ver sus debilidades',
    searchPlaceholder:'ej. poochyena, charizard…',
    advancedBtn:'Avanzado', genLabel:'Generación', latestGen:'Actual (Gen 9)',
    abilityLabel:'Anular hab.', noneOption:'— ninguna —', languageLabel:'Idioma',
    searchHint:'Sin resultados — prueba en inglés',
    clearHistory:'Borrar historial',
  },
  it: {
    weaknesses:'DEBOLEZZE', baseStats:'STATISTICHE', abilities:'ABILITÀ',
    evoChain:'CATENA EVOLUTIVA', forms:'FORME', default_:'BASE', with_:'CON',
    weak4:'DEBOLEZZA ×4', weak2:'DEBOLEZZA ×2', immune:'IMMUNITÀ ×0',
    resist2:'RESISTENTE ×½', resist4:'RESISTENTE ×¼',
    noMatchups:'Nessun risultato notevole',
    hp:'PS', atk:'Att', def:'Dif', spatk:'At.Sp', spdef:'Di.Sp', speed:'Vel',
    special:'Speciale', total:'Totale',
    levelUp:'Livello', tmhm:'MT / MN', breeding:'Uovo', tutor:'Tutoraggio', priorEvo:'Pre-evo.',
    colLv:'LV', colMove:'MOSSA', colType:'TIPO', colCat:'CAT', colPwr:'POT', colAcc:'PRE', colPp:'PP',
    catPhysical:'Fisico', catSpecial:'Speciale', catStatus:'Stato',
    ha:'HA', movesBtn:'Mosse', evolvesFrom:'si evolve da',
    friendship:'amicizia', trade:'scambio', day:'giorno', night:'notte',
    rain:'pioggia', flip:'capovolgere', beauty:'bellezza', affection:'affetto', special_:'speciale',
    loading:'Caricamento…', noDesc:'Nessuna descrizione disponibile.',
    failedMoves:'Impossibile caricare le mosse.', noMoveData:'Nessun dato sulle mosse.',
    noMovesInCat:'Nessuna mossa in questa categoria.',
    subtitle:'Inserisci il nome di un Pokémon per vedere le sue debolezze',
    searchPlaceholder:'es. poochyena, charizard…',
    advancedBtn:'Avanzato', genLabel:'Generazione', latestGen:'Attuale (Gen 9)',
    abilityLabel:'Forza abilità', noneOption:'— nessuna —', languageLabel:'Lingua',
    searchHint:'Nessun risultato — prova in inglese',
    clearHistory:'Cancella cronologia',
  },
  ja: {
    weaknesses:'弱点', baseStats:'種族値', abilities:'特性',
    evoChain:'進化', forms:'フォルム', default_:'通常', with_:'込み',
    weak4:'弱点 ×4', weak2:'弱点 ×2', immune:'無効 ×0',
    resist2:'耐性 ×½', resist4:'耐性 ×¼',
    noMatchups:'なし',
    hp:'HP', atk:'こうげき', def:'ぼうぎょ', spatk:'とくこう', spdef:'とくぼう', speed:'すばやさ',
    special:'とくしゅ', total:'合計',
    levelUp:'レベルアップ', tmhm:'わざマシン', breeding:'タマゴ', tutor:'おしえわざ', priorEvo:'前進化',
    colLv:'Lv', colMove:'わざ', colType:'タイプ', colCat:'分類', colPwr:'威力', colAcc:'命中', colPp:'PP',
    catPhysical:'物理', catSpecial:'特殊', catStatus:'変化',
    ha:'夢', movesBtn:'わざ', evolvesFrom:'から進化',
    friendship:'なつき', trade:'通信交換', day:'昼', night:'夜',
    rain:'雨', flip:'ひっくり返す', beauty:'美しさ', affection:'なかよし', special_:'特殊',
    loading:'読み込み中…', noDesc:'説明なし。',
    failedMoves:'読み込み失敗。', noMoveData:'わざデータなし。',
    noMovesInCat:'このカテゴリにわざはありません。',
    subtitle:'ポケモンの名前を入力して弱点を確認',
    searchPlaceholder:'例: ポチエナ、リザードン…',
    advancedBtn:'詳細', genLabel:'世代', latestGen:'最新 (Gen 9)',
    abilityLabel:'とくせい変更', noneOption:'— なし —', languageLabel:'言語',
    searchHint:'結果なし — 英語で検索してみて',
    clearHistory:'履歴を消す',
  },
  ko: {
    weaknesses:'약점', baseStats:'종족값', abilities:'특성',
    evoChain:'진화', forms:'폼', default_:'기본', with_:'포함',
    weak4:'약점 ×4', weak2:'약점 ×2', immune:'무효 ×0',
    resist2:'저항 ×½', resist4:'저항 ×¼',
    noMatchups:'없음',
    hp:'HP', atk:'공격', def:'방어', spatk:'특공', spdef:'특방', speed:'스피드',
    special:'특수', total:'합계',
    levelUp:'레벨 업', tmhm:'기술머신', breeding:'교배', tutor:'전수기', priorEvo:'이전 진화',
    colLv:'Lv', colMove:'기술', colType:'타입', colCat:'분류', colPwr:'위력', colAcc:'명중', colPp:'PP',
    catPhysical:'물리', catSpecial:'특수', catStatus:'변화',
    ha:'꿈', movesBtn:'기술', evolvesFrom:'에서 진화',
    friendship:'친밀도', trade:'통신교환', day:'낮', night:'밤',
    rain:'비', flip:'뒤집기', beauty:'아름다움', affection:'포켓레', special_:'특수',
    loading:'불러오는 중…', noDesc:'설명 없음.',
    failedMoves:'불러오기 실패.', noMoveData:'기술 데이터 없음.',
    noMovesInCat:'이 카테고리에 기술이 없습니다.',
    subtitle:'포켓몬 이름을 입력하여 약점 확인',
    searchPlaceholder:'예: 포치에나, 리자몽…',
    advancedBtn:'고급', genLabel:'세대', latestGen:'최신 (Gen 9)',
    abilityLabel:'특성 변경', noneOption:'— 없음 —', languageLabel:'언어',
    searchHint:'결과 없음 — 영어로 검색해 보세요',
    clearHistory:'기록 지우기',
  },
  'zh-Hans': {
    weaknesses:'弱点', baseStats:'种族值', abilities:'特性',
    evoChain:'进化', forms:'形态', default_:'默认', with_:'含',
    weak4:'弱点 ×4', weak2:'弱点 ×2', immune:'无效 ×0',
    resist2:'抵抗 ×½', resist4:'抵抗 ×¼',
    noMatchups:'无',
    hp:'HP', atk:'攻击', def:'防御', spatk:'特攻', spdef:'特防', speed:'速度',
    special:'特殊', total:'合计',
    levelUp:'升级', tmhm:'招式机器', breeding:'遗传', tutor:'传授招式', priorEvo:'前进化',
    colLv:'LV', colMove:'招式', colType:'属性', colCat:'分类', colPwr:'威力', colAcc:'命中', colPp:'PP',
    catPhysical:'物理', catSpecial:'特殊', catStatus:'变化',
    ha:'梦', movesBtn:'招式', evolvesFrom:'从…进化',
    friendship:'亲密度', trade:'通信交换', day:'白天', night:'夜晚',
    rain:'雨天', flip:'翻转', beauty:'美丽', affection:'喜爱', special_:'特殊',
    loading:'加载中…', noDesc:'暂无描述。',
    failedMoves:'加载失败。', noMoveData:'无招式数据。',
    noMovesInCat:'该分类中没有招式。',
    subtitle:'输入宝可梦名称以查看弱点',
    searchPlaceholder:'例：泥泥狗、喷火龙…',
    advancedBtn:'高级', genLabel:'世代', latestGen:'最新 (Gen 9)',
    abilityLabel:'覆盖特性', noneOption:'— 无 —', languageLabel:'语言',
    searchHint:'无结果 — 请用英文搜索',
    clearHistory:'清除历史',
  },
  'zh-Hant': {
    weaknesses:'弱點', baseStats:'種族值', abilities:'特性',
    evoChain:'進化', forms:'形態', default_:'預設', with_:'含',
    weak4:'弱點 ×4', weak2:'弱點 ×2', immune:'無效 ×0',
    resist2:'抵抗 ×½', resist4:'抵抗 ×¼',
    noMatchups:'無',
    hp:'HP', atk:'攻擊', def:'防禦', spatk:'特攻', spdef:'特防', speed:'速度',
    special:'特殊', total:'合計',
    levelUp:'升級', tmhm:'招式機器', breeding:'遺傳', tutor:'傳授招式', priorEvo:'前進化',
    colLv:'LV', colMove:'招式', colType:'屬性', colCat:'分類', colPwr:'威力', colAcc:'命中', colPp:'PP',
    catPhysical:'物理', catSpecial:'特殊', catStatus:'變化',
    ha:'夢', movesBtn:'招式', evolvesFrom:'從…進化',
    friendship:'親密度', trade:'通訊交換', day:'白天', night:'夜晚',
    rain:'雨天', flip:'翻轉', beauty:'美麗', affection:'喜愛', special_:'特殊',
    loading:'載入中…', noDesc:'暫無描述。',
    failedMoves:'載入失敗。', noMoveData:'無招式資料。',
    noMovesInCat:'該分類中沒有招式。',
    subtitle:'輸入寶可夢名稱以查看弱點',
    searchPlaceholder:'例：土狗仔、噴火龍…',
    advancedBtn:'高級', genLabel:'世代', latestGen:'最新 (Gen 9)',
    abilityLabel:'覆蓋特性', noneOption:'— 無 —', languageLabel:'語言',
    searchHint:'無結果 — 請用英文搜尋',
    clearHistory:'履歴を消す',
  },
  'ja-Hrkt': {
    weaknesses:'じゃくてん', baseStats:'しゅぞくち', abilities:'とくせい',
    evoChain:'しんか', forms:'フォルム', default_:'ノーマル', with_:'いり',
    weak4:'じゃくてん ×4', weak2:'じゃくてん ×2', immune:'むこう ×0',
    resist2:'たいせい ×½', resist4:'たいせい ×¼',
    noMatchups:'なし',
    hp:'HP', atk:'こうげき', def:'ぼうぎょ', spatk:'とくこう', spdef:'とくぼう', speed:'すばやさ',
    special:'とくしゅ', total:'ごうけい',
    levelUp:'レベルアップ', tmhm:'わざマシン', breeding:'タマゴ', tutor:'おしえわざ', priorEvo:'ぜんしんか',
    colLv:'Lv', colMove:'わざ', colType:'タイプ', colCat:'ぶんるい', colPwr:'いりょく', colAcc:'めいちゅう', colPp:'PP',
    catPhysical:'ぶつり', catSpecial:'とくしゅ', catStatus:'へんか',
    ha:'ゆめ', movesBtn:'わざ', evolvesFrom:'からしんか',
    friendship:'なつき', trade:'つうしんこうかん', day:'ひるま', night:'よる',
    rain:'あめ', flip:'ひっくりかえす', beauty:'うつくしさ', affection:'なかよし', special_:'とくしゅ',
    loading:'よみこみちゅう…', noDesc:'せつめいなし。',
    failedMoves:'よみこみしっぱい。', noMoveData:'わざデータなし。',
    noMovesInCat:'このカテゴリにわざはありません。',
    subtitle:'ポケモンのなまえをにゅうりょくしてじゃくてんをかくにん',
    searchPlaceholder:'れい: ポチエナ…',
    advancedBtn:'しょうさい', genLabel:'せだい', latestGen:'さいしん (Gen 9)',
    abilityLabel:'とくせいへんこう', noneOption:'— なし —', languageLabel:'げんご',
    searchHint:'けっかなし — えいごでけんさく',
    clearHistory:'りれきをけす',
  },
  roomaji: {
    weaknesses:'Jakuten', baseStats:'Shuzoku-chi', abilities:'Tokusei',
    evoChain:'Shinka', forms:'Forumu', default_:'Tsūjō', with_:'Iri',
    weak4:'Jakuten ×4', weak2:'Jakuten ×2', immune:'Mukō ×0',
    resist2:'Taisei ×½', resist4:'Taisei ×¼',
    noMatchups:'Nashi',
    hp:'HP', atk:'Kōgeki', def:'Bōgyo', spatk:'Tokkō', spdef:'Tokubō', speed:'Subayasa',
    special:'Tokushu', total:'Gōkei',
    levelUp:'Reberu Appu', tmhm:'Waza Mashin', breeding:'Tamago', tutor:'Oshie Waza', priorEvo:'Mae Shinka',
    colLv:'Lv', colMove:'WAZA', colType:'TAIPU', colCat:'BUNRUI', colPwr:'IRYOKU', colAcc:'MEICHŪ', colPp:'PP',
    catPhysical:'Butsuri', catSpecial:'Tokushu', catStatus:'Henka',
    ha:'Yume', movesBtn:'Waza', evolvesFrom:'kara shinka',
    friendship:'natsuki', trade:'tsūshin kōkan', day:'hiruma', night:'yoru',
    rain:'ame', flip:'hikkuri kaesu', beauty:'utsukushisa', affection:'nakayoshi', special_:'tokushu',
    loading:'Yomikomi chū…', noDesc:'Setsumei nashi.',
    failedMoves:'Yomikomi shippai.', noMoveData:'Waza dēta nashi.',
    noMovesInCat:'Kono kategori ni waza wa arimasen.',
    subtitle:'Pokémon no namae wo nyūryoku shite jakuten wo kakunin',
    searchPlaceholder:'rei: Pochie na, Rizādon…',
    advancedBtn:'Shōsai', genLabel:'Sedai', latestGen:'Saishin (Gen 9)',
    abilityLabel:'Tokusei henkou', noneOption:'— nashi —', languageLabel:'Gengo',
    searchHint:'Kekka nashi — Eigo de kensaku',
    clearHistory:'Rireki wo kesu',
  },
};

// Fallback chain: currentLang → en → raw key (so untranslated keys still render something).
function t(key) {
  return (UI_STRINGS[currentLang] || UI_STRINGS.en)[key] ?? UI_STRINGS.en[key] ?? key;
}

