services:
  weakness-dex:
    image: ghcr.io/xoudusz/weakness-dex:latest
    container_name: weakness-dex
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
