name               = "weakness-dex-og"
main               = "index.js"
compatibility_date = "2025-01-01"

[build]
command = "npm install"

[[routes]]
pattern   = "weakness-dex.hyvitech.org/*"
zone_name = "hyvitech.org"
